### ISSUE TITLE
Не работает сам перевод просто копирует английский файл

### ISSUE THREAD

**Issue by icefreesky** [Sim-fo/renpy_translate#1]
просто пробрасывает и даже не пытается переводить до этого получалось

**Comment by Sim-fo** [comment]
Гугл может блокировать на день-два, если переведено много текста. В остальном должно работать. Хотя эта версия уже сильно старая.. много ошибок остается после перевода. Постараюсь найти и залить версию новее.

**Comment by icefreesky** [comment]
Спасибо огромное, этот скрипт очень нужная штука )
